os:
  - linux
services:
  - docker
language: java
sudo: true
jdk:
    - openjdk8
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - MAVEN_USER_HOME=$HOME/.m2/repository/
before_install:
  - java -version
#install:
#  - . install
script:
  - chmod +x mvnw
  - ./mvnw -ntp checkstyle:check
  - ./mvnw -ntp clean verify
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then ./mvnw -ntp org.jacoco:jacoco-maven-plugin:prepare-agent initialize sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN; fi
  - ./mvnw -ntp verify -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
