spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 主库数据源
    druid:
      main:
        url: jdbc:mysql://10.129.248.10:55100/bim5d_cost_main
        username: root
        password: 123qwe!@#
      enterprise:
        url: jdbc:mysql://10.129.248.10:55100/bim5d_cost_o201804999390208
        username: root
        password: 123qwe!@#
      project:
        url: jdbc:mysql://10.129.248.10:55100/bim5d_cost_p230414496670720
        username: root
        password: 123qwe!@#
think:
  generator:
    enabled: true
    configuration:
      frame-name: com.glodon.bim5d
      company-name: com.glodon.bim5d
      app-name: bim5d
      module-name: costenterprise
#      module-name: costproject
      author-name: unascribed
      namespace: view
      template: template/glodon/enterprise
#      template: template/glodon/project
      extensions:
        - java
        - js
        - jsp
        - xml
        - ts
        - html
        - json
        - sql
      converts: {
        "java.sql.Types.BIGINT" : "java.math.BigInteger"
#        "java.sql.Types.DATE": "java.time.LocalDate"
#        "java.sql.Types.TIMESTAMP": "java.time.Instant"
      }
      prefixs:
        - BIM5D_COST_
      ignores:
        - sys_create_time
        - sys_modified_time
        - sys_revision
        - sys_creator_id
        - sys_modifier_id
      output: generator_output
